language: cpp
os: linux
dist: bionic
compiler: gcc
branches:
  only:
    - master
    - "2.0"
    - appimage
matrix:
  fast_finish: true
  include:
  - compiler: gcc
    env: ANALYZE="scan-build -o out " GH_REF=github.com/LibreCAD/static-analyzer-reports.git
  allow_failures:
  - env: ANALYZE="scan-build -o out " GH_REF=github.com/LibreCAD/static-analyzer-reports.git
install:
- sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.6-bionic
- sudo apt -y update
- sudo apt -qq install qt512-meta-full libgl-dev libmuparser-dev libboost-dev libfreetype6-dev libicu-dev pkg-config
- source /opt/qt512/bin/qt512-env.sh
- |
  if [ "${ANALYZE}" ]; then
    wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -;
    echo "yes" | sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc) main";
    sudo apt update;
    sudo apt -qq install clang-tools-6.0;
  fi;
script:
- ${ANALYZE}qmake -r librecad.pro CONFIG+=debug_and_release
- ${ANALYZE}make release -j$(nproc)
- if [ "${ANALYZE}" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./CI/static-analyzer-reports.sh; fi
- ./CI/build-appimg.sh
- ls -laR
