find_program(TRANSLATOR NAMES lrelease)
if(NOT TRANSLATOR)
    message(FATAL_ERROR "Qt translator 'lrelease' not found")
endif()

# TODO is APPLE really among to UNIX
if(UNIX)
    if(APPLE)
        message("This ins apple")
#        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/apple/lib)
#        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/apple/lib)
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/apple/bin)
    else(APPLE)
        message("This is unix")
#        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/unix/lib)
#        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/unix/lib)
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/unix/bin)
    endif(APPLE)
#    add_compile_options(-Wall -Wextra -pedantic -Werror)
    add_compile_options(-Wall -Wextra -pedantic)
else(UNIX)
    message("This is windows")
#    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/windows/lib)
#    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/windows/lib)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/windows/bin)
#    add_compile_options(/W4 /WX)
    add_compile_options(/W4)
endif(UNIX)

